all:
	g++ main.cpp objects/lightSource.cpp editor/window.cpp player/camera.cpp game.cpp common.cpp objects/shapes.cpp objects/mesh.cpp objects/model.cpp objects/shader.cpp objects/texture.cpp libs/glad.c -o main -ldl -lGLU -lglut -lGL -lassimp -lglfw -w
run:
	./main